### ISSUE TITLE
URGENT: REPO created incorrectly 😳

### ISSUE THREAD

**Issue by elasticdotventures** [Leathong/openscad-support-vscode#1]
Hi @Leathong ,

This request is rather urgent before you do much work. 

I noticed this repo wasn't properly forked from earlier work of @Antyos [Antyos/vscode-openscad](https://github.com/Antyos/vscode-openscad), meaning any contributions I make to your copy don't have a fresh commit log.  

I'm sorry, I can't use your repo because it doesn't contain the proper git lineage.
I urge anybody consider looking at this repo to consider making upstream contributions from there.  (don't make the mistake I was about to)

to @Leathong - To fix:
create a fork of a repo rather than a fresh copy, this way it's easy to tell who/when changes we introduced using git-blame and related tools, and therefore it's also easier to coordinate the work of many developers to work on the same project, and benefit from each others work. 

Setting | (scroll to bottom) | Delete this Repo
then (before beginning any work) go to your closest upstream

Cheers!

**Comment by Antyos** [comment]
Thanks for bringing this to my attention @elasticdotventures (It certainly helped to put URGENT in the title).

If you are interested @Leathong, I would be happy to review a PR to add a language server to [Antyos/vscode-openscad](https://github.com/Antyos/vscode-openscad) instead of having to implement it as its own extension.

**Comment by elasticdotventures** [comment]
After Settings | (scroll to bottom) | Delete this Repo
then (before beginning any work) go to your closest upstream:
```bash
# using github client
gh repo fork https://github.com/Antyos/vscode-openscad
```
then you can submit pull requests to the Antyos vscode-openscad

**Comment by Leathong** [comment]
@Antyos @elasticdotventures

**Comment by Leathong** [comment]
@Antyos @elasticdotventures 
Sorry for the late reply. I built on your great work because I really liked the preview feature, but the other features were redundant for me, such as export, snippets etc, OpenSCAD itself had those features or some implemented by LSP, and they added too many buttons that could lead to misuse, so I removed most of them, therefore this project is no longer suitable to merge back.
